image: node

stages:
  - build
  - lint
  - test

cache:
  paths:
    - $HOME/.cache/firebase
    - .npm/
    - node_modules/

build:
  stage: build
  script:
    - yarn install
    - yarn run build

lint:
  stage: lint
  script:
    - yarn run lint

unittest:
  stage: test
  before_script:
    - apt-get install -y openjdk-8-jdk
    - npm install -g firebase-tools
  script:
    - firebase emulators:exec --only firestore  'yarn run test:src'


e2e:
  stage: test
  before_script:
    - apt-get install -y openjdk-8-jdk
    - npm install -g firebase-tools
  script:
    - yarn run dev &
    - firebase emulators:exec --import=firebase-emulators-data 'yarn run test:e2e'
