image: node

stages:
  - build
  - lint
  - unittest
  - e2e

cache:
  paths:
    - .cache/Cypress
    - .npm/
    - node_modules/

build:
  stage: build
  script:
    - yarn install
    - yarn build

lint:
  stage: lint
  script:
    - yarn run lint

unittest:
  stage: unittest
  script:
    - npm i -g mocha firebase-tools
    - firebase emulators:exec --only firestore 'yarn run test_sec'


e2e:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: e2e
  script:
    - apt-get update && apt-get install -y openjdk-8-jdk
    - npm i -g firebase-tools
    - firebase emulators:exec --import=firebase-emulators-data 'yarn dev & yarn e2e'
