image: node

stages:
  - build
  - lint
  - test

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn install
    - yarn run build

lint:
  stage: lint
  script:
    - yarn run lint

unittest_and_e2e:
  stage: test
  before_script:
    - echo $FIREBASE_TOKEN
    - apt-get update && apt-get install -y openjdk-8-jre
    - curl -sL https://firebase.tools | bash
  script:
    - firebase emulators:exec --token $FIREBASE_TOKEN --project default --only firestore 'yarn run test:sec'
    - yarn run dev &
    - firebase emulators:exec --token $FIREBASE_TOKEN --project default --import=firebase-emulators-data 'yarn run test:e2e'
