image: node

stages:
  - build
  - lint
  - test

cache:
  paths:
    - node_modules/
    - /root/.cache/firebase/emulators

build:
  stage: build
  script:
    - yarn install

lint:
  stage: lint
  script:
    - yarn run lint

test:
  stage: test
  before_script:
    - apt-get update && apt-get install -y openjdk-8-jre
    - yarn global add firebase-tools
  script:
    - firebase emulators:exec --token $FIREBASE_TOKEN --only firestore 'yarn run test:unit'
    - yarn run dev &
    - firebase emulators:exec --token $FIREBASE_TOKEN --import=firebase-emulators-data 'yarn run test:e2e'
